### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Climu1d** [ymgaq/AQ#103]
When will be the next update?

**Comment by Climu1d** [comment]
To clarify, will there be a new release of aq?

**Comment by john45678** [comment]
Would love to see a new release soon.

**Comment by ymgaq** [comment]
Hi guys.

I am so busy, sorry that maintenance of this repository was not adequate. However, development continues, of course.

As you know, [Facebook](https://github.com/pytorch/ELF) and [Tencent](https://github.com/Tencent/PhoenixGo) released a very strong bot with AlphaGo reimplementation. This method requires a lot of resources, perhaps it will still take some time to catch up even with a smart distributed system like [Leela Zero](https://github.com/gcp/leela-zero).

AQ is currently being developed with a completely different approach, and it is necessary to review all existing codes. Hopefully, the next version (probably 3.0.0) is going to release around this summer, so please wait for a while.

**Comment by sinhayday** [comment]
i love to hear new version of aq will be released this summer.
thank to ymg thanks a lot.

**Comment by wonsiks** [comment]
I'm looking forward to see it.
Cheers~

**Comment by l1t1** [comment]
nice jobs in 
 2018 Tencent World AI Weiqi Competition 
and
2018 Chinese weiqi congress

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
