### ISSUE TITLE
emmm

### ISSUE THREAD

**Issue by XYC-EXP** [ymgaq/AQ#109]
// Linux(Ubuntu18.04)

> ./AQ
error while loading shared libraries: libcusolver.so.8.0: cannot open shared object file: No such file or directory

But the file is there.

**Comment by greatken999** [comment]
you can use "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/where you install aq path" to fix this

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
