### ISSUE TITLE
How can I run AQ in Gogui?

### ISSUE THREAD

**Issue by bclman** [ymgaq/AQ#12]
AQ is very strong.
AQ always wins Leela0.11. 
I run AQ in Ubuntu terminal, but I can't run AQ in Gogui or sabaki.
How can I run AQ in Gogui?
![20170924_051603](https://user-images.githubusercontent.com/32253256/30791098-357fa714-a1eb-11e7-8903-027af90d3393.jpg)
![20170924_051626](https://user-images.githubusercontent.com/32253256/30791099-359a2b52-a1eb-11e7-854f-f60c1dce7f44.jpg)

**Comment by a22063821** [comment]
command: ./AQ
working directory: (installed directory)

**Comment by bclman** [comment]
command: ./AQ
working directory: (installed)
But, I can't run AQ in gogui.

![20170925_141751](https://user-images.githubusercontent.com/32253256/30793432-eda1eeb8-a1fc-11e7-8835-a466a8a1c20b.jpg)
![20170925_141801](https://user-images.githubusercontent.com/32253256/30793447-f70bac6e-a1fc-11e7-9628-97262053e477.jpg)

**Comment by a22063821** [comment]
try english directory

**Comment by bclman** [comment]
English directory didn't work.
AQ works properly only in Ubuntu terminal at my PC.

![2017-09-25 18-31-20](https://user-images.githubusercontent.com/32253256/30802064-4957fe96-a220-11e7-8b2b-a8d9700f0c98.png)
![2017-09-25 18-31-42](https://user-images.githubusercontent.com/32253256/30802066-495d4f22-a220-11e7-8b32-3f31dccc399d.png)
![2017-09-25 18-32-20](https://user-images.githubusercontent.com/32253256/30802065-495b9ccc-a220-11e7-9b07-0b8c9f76238f.png)

**Comment by ymgaq** [comment]
You should set:
Command: (your directory path)/AQ/AQ
Working directory: (your directory path)/AQ

Also turn off 'self_match' in the configure file for launching with GTP mode.

**Comment by bclman** [comment]
I tried, but I can't.

![2017-09-26 01-41-49](https://user-images.githubusercontent.com/32253256/30820987-a15bf4f6-a25e-11e7-9475-1ec92d16dd9c.png)
![2017-09-26 01-42-10](https://user-images.githubusercontent.com/32253256/30820988-a162f9a4-a25e-11e7-8291-046ff649c34f.png)

**Comment by ymgaq** [comment]
You cannot run AQ simultaneously on both the terminal and GoGui. 
Use the GTP Shell of GoGui if you want to see outputs.

**Comment by bclman** [comment]
Go
![2017-09-26 18-23-34](https://user-images.githubusercontent.com/32253256/30852844-12f49c92-a2e8-11e7-8805-2068af2ee2a3.png)
![2017-09-26 18-23-43](https://user-images.githubusercontent.com/32253256/30852843-12de7b4c-a2e8-11e7-9f92-f5764cac4c36.png)




gui in my PC(Ubuntu 16.04) can't open AQ.

**Comment by ymgaq** [comment]
Anyway you should show the error output displayed in the GTP Shell. Otherwise we cannot identify what is wrong.

**Comment by zakki** [comment]
GNU Go and Ray returns
```
list_commands
=
boardsize
clear_board
...

```

But, AQ seems to return
```
list_commands
= boardsize
= list_commands
...

```

Is it OK?

**Comment by ymgaq** [comment]
The response of AQ does not follow to the GTP protocol (even now, it seems to work on CGOS etc.), so I will fix it to be separated by a single LF in the next version. 

However, I think GoGui does not send 'list_commands' by default, so this problem seems to have another cause.

**Comment by as0770** [comment]
AQ works in GoGui here. Sometimes it needs long for the initialization and GoGui says: Engine does not respond: wait/quit. When pressing wait it works:

```
name
= AQ

protocol_version
= 2.0.2

version
= 2.0.2

list_commands
= boardsize
= list_commands
= clear_board
= genmove
= play
= quit
= time_left
= time_settings
= name
= version
= 

boardsize 19
= 

clear_board
= 

play B Q16
= 

play W D16
= 

play B R4
= 

play W D3
= 

play B C5
= 

play W P3
= 

play B M4
= 

I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
```

**Comment by bclman** [comment]
I solved the problem.
/etc/ld.so.conf.d---> make nvidia.conf file--> /usr/local/cuda-8.0/lib64
sudo ldconfig
Now AQ works in Gogui.
