### ISSUE TITLE
Can I use CPU only?

### ISSUE THREAD

**Issue by uestccokey** [ymgaq/AQ#17]
Can I run AQ on a CPU only computer?

**Comment by uestccokey** [comment]
Haha,@wjx0912,Thanks for your reply,I like the '静思围棋' you developed!
I want to transplant the AQ's policy network to the Android phone, but I find that 'sl_0.pb' needs device:GPU0, and the Android phone only has CPU, so it will be wrong.

**Comment by wjx0912** [comment]
@uestccokey ,maybe you need retraining and replace .pb files, i like the '掌中围棋' also, keep on going~

**Comment by y-ich** [comment]
I ported AQ for macOS without GPU.
https://github.com/y-ich/AQ/tree/mac_cpu

pb/sl_0.pb and pb/vl_0.pb in it are the ones that device attributes were removed in.

**Comment by uestccokey** [comment]
@y-ich coooool! I will test it.many thanks.

**Comment by ymgaq** [comment]
The latest version is supporting CPU-only mode.
See [Release](https://github.com/ymgaq/AQ/releases) page and try it.
(Currently the distribution executable file without GPU is only for Windows.)

You can build from source code the executable file for Linux or other OS.
See [this instruction](https://medium.com/jim-fleming/loading-a-tensorflow-graph-with-the-c-api-4caaff88463f).

**Comment by uestccokey** [comment]
ok,thank you
