### ISSUE TITLE
[Feature request] Show in engine output win-rate || var clarification

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [ymgaq/AQ#20]
Hello!
If it possible - could win-rate be added to putput? Or 'value' is 100% representation if gerenal win-date? 
Accodring next example it can't be it.

Also asking because other engines provide several types of win-rate.

Could you clarify what exactly the meaning of next vars:
value | roll | prob

For example engine has next output:
|move|count  |value|roll |prob |depth|
|C15 |  11300| 16.3| 38.2|  4.7  |   15|
|D15 |   6293| 15.5| 38.1 | 29.3 |   24|

prob is higher for D15 but engine played C15. 
value is 15.5-16.3 but it's only 10 move of standart opening, so it can't be win-rate. 

Attached screenshot.

Thank you!

![600 15-oct-17 14 29](https://user-images.githubusercontent.com/7886823/31584351-69d680bc-b1b5-11e7-8ffd-588bc446adb6.jpg)

**Comment by ymgaq** [comment]
The stones are exchanged when reading from sgf files on Sabaki as mentioned #19.
 (In the above screen shot, AQ recognizes C4 is black stone!)

count : searching count for this move
value : evaluated value with the value network
roll : winning rate of roll out
prob : evaluated probability with the policy network
depth : searching depth of this move.

AQ internally mixes 'value' and 'roll', but up to 200 hands are mainly referring to value. Therefore, in many cases, I think it is the best choice to see value as winning percentage.

**Comment by aTan-aka-Xellos** [comment]
I understand issue with #19  but not sure that it's affect direct game (not loaded record). Cause it play totally fine. I just finished match AQ vs Leela 11b via Sabaki with long time settings and it's totally fine. If it had recognized stones incorrectly - game would just collapse but it's not.

So I can't understand how pure value can be refered as win-rate in traditional meaning.
For example using engine output with win-rate it was possible to build win-rate chart line in attached screenshot. But with current AQ output - it will be impossible. 
So what I mean - this feature very useful if use engine to analyze games. 

![594 14-oct-17 19 06](https://user-images.githubusercontent.com/7886823/31585058-5fca1c56-b1c3-11e7-8993-88d333ad0497.jpg)

**Comment by ymgaq** [comment]
I usually refer 'value' as winning rate for analyzing game, so you can plot the chart using 'value'.

If you absolutely want to calculate the internal proportion, use the following formula:
lambda * value + (1-lambda) * rollout_rate
where lambda = 0.8 - min(0.3, max(0.0, (move_cnt - 160) / 600)).

**Comment by pnprog** [comment]
Hello!

> lambda * value + (1-lambda) * rollout_rate
> where lambda = 0.8 - min(0.3, max(0.0, (move_cnt - 160) / 600)).

Could you confirm that **move_cnt** is the **count** column, and **rollout_rate** is the **roll** column?

If yes, then, to take the example above from **aTan-aka-Xellos**, and running your calculation, I get this result:

variation | count | value | roll | lambda | win rate
-- | -- | -- | -- | -- | --
C15 | 11300 | 16.3 | 38.2 | 0.50 | 27,25%
D15 | 6293 | 15.5 | 38.1 | 0.50 | 26,8%

Is that all right?

I am the author of [Go Review Partner](https://github.com/pnprog/goreviewpartner), I am interested to add support for AQ.

**Comment by ymgaq** [comment]
> Could you confirm that move_cnt is the count column, and rollout_rate is the roll column?

Yes.

> Is that all right?

No, the the lambda is 0.8 until 160th move and then decreases to 0.5.
In the above example, it is on 12th move, so the internal 'winning rates' should be about 20.7% and 20.0%.

However, as mentioned, I usually use 'value' as winning rate because the roll out of AQ is really poor.

> I am the author of Go Review Partner, I am interested to add support for AQ.

Great! I am very much pleased that your software will support for AQ.

**Comment by pnprog** [comment]
Hi!

Thanks for the clarification, I started implementing support for AQ, so far so good :)

> No, the the lambda is 0.8 until 160th move and then decreases to 0.5.
In the above example, it is on 12th move, so the internal 'winning rates' should be about 20.7% and 20.0%.
> However, as mentioned, I usually use 'value' as winning rate because the roll out of AQ is really poor.

I have been tested both methods, but I am not sure which one to use.

I need your help to clarify something: If we continue with the example above, it's white to play, and the move selected by **AQ** is **C15**. The win rate probability for white can be calculated using your formula or simply using the roll out.

My question is, can we simply calculate the win rate probability for black by subtracting white win rate to 100% ? That would give:

Method | White win rate | Black win rate
-- | -- | --
Calculated | 20.70 % | **79.30 %**
Roll out | 38.20 % | **61.80 %**

When doing this, I notice big swings between win rates of two consecutive moves.

**Comment by aTan-aka-Xellos** [comment]
The issue is that judging from this position both values can't be valid. 
C15 win-rate should be 50% +/-3%, well +/-5% at most. Smaller or bigger value is not possible in this position because it obviously even. 
Others go engines (leela/ray) win-rate implementation estimate it as even as well.

**Comment by pnprog** [comment]
Hi!

I made a comparison between AQ win rate (both method), Leela and Ray (all of them CPU only, 30s per move), on the same game (KeJie-Alphago in Wuzhen on 2017-05-23):
![all](https://user-images.githubusercontent.com/25114663/31924367-31d5edba-b8b3-11e7-9893-90de4e8c0bd9.png)
From that, one can see both methods are consistent, but I think the calculation method is a bit more similar with Leela win rate than the roll method, so I will probably keep that one in the end :)

PS: Ray appears to be a bit off, I think my computer is too slow for Ray :(

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
