### ISSUE TITLE
CGOS config

### ISSUE THREAD

**Issue by kris-computer-go** [ymgaq/AQ#21]
What should be time settings for playing on CGOS.
I've tried two variants:
-main time[sec] =900
-byoyomi[sec] =0
-time controll =on
or
-time controll =off
in both cases AQ loosing sometimes by time

**Comment by ymgaq** [comment]
As described in [README](https://github.com/ymgaq/AQ/blob/master/README.md), the following setting is recommended:

```
-main time[sec] =900  
-byoyomi[sec] =0  
-time controll =off  
```

AQ will enter the emergency mode and return a move within 0.1 sec when the remaining time is less than 15 sec. In my test, AQ has never lost due to out of time. (excluding CGOS client problems)

However, if your network causes a delay to the CGOS server, it is likely to be lost, so I don't recommend testing on CGOS with such environment.

**Comment by kris-computer-go** [comment]
Is it a problem to add support for time_setting command?

**Comment by ymgaq** [comment]
No, so I will implement it in the next version.

**Comment by kris-computer-go** [comment]
Thanks for your response

**Comment by aTan-aka-Xellos** [comment]
also have issues that AQ lose by time sometimes. Set -time controll =off  but didn't help. But I didn't set -main time[sec] =900 as you mentioned here - not included in that comment in config. Will test with it.

Could you tell please what the hardware of AQ-2.0.3 were used? 
Right now testing with nickname 'AQ_i5_GTX1080'.

Also what this setting are doing? 

-symmetrical index
-mimic go
-self match (assume it play with itself, but how exactly to use?)

Thank you.

**Comment by ymgaq** [comment]
I think that the hardware of AQ-2.0.３ was

CPU: i7 6700K (4core/8thread)
GPU: GTX1080 (x1)

and configuration is:

```
-symmetrical index=0
-mimic go=off
-self match=off
```

The detailed information is mentioned in #9
`self match` flag is just for debug, so you should not change the setting.

**Comment by Borthralla** [comment]
With time_control set to on, the main time seems to be reset every time for me. For example, if I set the main_time to be 30 seconds, the match goes on for longer than 1 minute and never goes to byo yomi. I'm using the latest windows version.

**Comment by pandoraaq** [comment]
I can not run him on cogs you have the config file and cgosGtp of AQ not. If so let me show you how

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
