### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by takamaru21** [ymgaq/AQ#23]
i loaded sgf . 
and i played game with AQ in tabaki.

but,.... 

![20171017_004433](https://user-images.githubusercontent.com/32845931/31621500-d3b1bdec-b2d4-11e7-9ef1-2c954511be25.png)

![20171017_004844](https://user-images.githubusercontent.com/32845931/31621553-f2708394-b2d4-11e7-8567-44b8b4a63928.png)

 Why am I getting an error?

**Comment by aTan-aka-Xellos** [comment]
@takamaru21 
Check https://github.com/ymgaq/AQ/issues/19 bug and download updated version.
