### ISSUE TITLE
handicap game

### ISSUE THREAD

**Issue by elpanor** [ymgaq/AQ#24]
Does AQ support handicap game?

In my test, AQ show illegal move in handicap game.

And when I change Komi, only roll out ratio change , Value count doesn change. Is it correct?

**Comment by ymgaq** [comment]
AQ supports `set_free_handicap` and `place_free_handicap` commands.
It works on GoGui in my environment.

Value network of AQ doesn't recognize Komi, so that it may misunderstand the situation in handicap games.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
