### ISSUE TITLE
Is there solution about "too many include files" problem when I compile AQ in window 7?

### ISSUE THREAD

**Issue by trainewbie** [ymgaq/AQ#25]
Hi.

I suffer from "C1013 too many include files // File : tensor //  Line :1" error during compiling.

How did you solve it?

**Comment by ymgaq** [comment]
I think it might occur due to the order of including directories.
See [this instruction](https://joe-antognini.github.io/machine-learning/windows-tf-project).

> First, the compiler needs to find all the appropriate Tensorflow header files. In your Additional Include Directories, add:
```
C:\Users\%USERNAME%\bin\tensorflow
C:\Users\%USERNAME%\bin\tensorflow\tensorflow\contrib\cmake\build
C:\Users\%USERNAME%\bin\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive
C:\Users\%USERNAME%\bin\tensorflow\third_party\eigen3
C:\Users\%USERNAME%\bin\tensorflow\tensorflow\contrib\cmake\build\protobuf\src\protobuf\src
```
> It is important to **put the eigen_archive directory above the eigen3 directory** — otherwise you’ll get the C1014 “too many include files” error.

**Comment by trainewbie** [comment]
Thanks for your answer.

I also read the upper link, and I followed that sequence.

Myabe, I did somethings wrong at the other part.

I have one favor. Can you upload your sln & object files for my refernce and comparison.

Regards.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
