### ISSUE TITLE
Can't make it work in Sabaki

### ISSUE THREAD

**Issue by ProperNovice** [ymgaq/AQ#26]
Hello all,

I have the latest AQ v2.0.3.1 and Sabaki v0.31.4.
Can someone help me how to add the engine to Sabaki?
I downloaded the AQ_win.zip file and extracted it.
I downloaded Sabaki. Then I go to: File -> Preferences -> Engines -> Add -> added the AQ.exe from the previous .zip
Then I go to: Engines -> Attach -> and put the AQ in either Black or White field.
- If I put it in Black then it 'thinks' indefinitely, changing the cursor to a circle but it doesn't use any CPU.
- If I put it in White, I play a move as Black then it passes the turn every time.

edit:

I tried GoGui as well and didn't manage to start it. I copied the AQ folder in GoGui's one. Then I went

Program - New Program - Setting command as 'C:\Games\GoGui\AQ\AQ.exe', Working directory as 'C:\Games\GoGui\AQ\' (both with the last ' \ ' and without it) and when I press 'Ok' I got the error:

'The go program terminated unexpectedly. The Go program did not respond to any commands. One possible reason is that the commend for executing the program in GTP mode was not correct.'

I have NVidia 670 with the latest drivers updated.

What am I doing wrong?

I want to run the engine, not caring about the GUI.

Thank you

John

**Comment by ymgaq** [comment]
I don't know much about Sabaki.
First of all, you should test with AQ in `self match` mode.
Set `self match` flag to be `on` in 'aq_config.txt.' 

In command prompt, 
```
> cd (install directory)   
(ex. C:\Users\%USERNAME%\AQ)
> AQ.exe
```
Then you may find what is wrong.

**Comment by ProperNovice** [comment]
Ok.

' api-ms-win-crt-runtime-l1-1-0.dll is missing. Try reinstalling the program. '

**Comment by ymgaq** [comment]
I think it is caused not by AQ but your system.
See [here](https://www.drivereasy.com/knowledge/api-ms-win-crt-runtime-l1-1-0-dll-missing-error-solved/) to solve the problem.

**Comment by ProperNovice** [comment]
Indeed. Thank you very much. We have targeted the problem now

**Comment by tartaric** [comment]
ProperNovice, can you explain totally to me how to make AQ working on Sabaki cause I tried but It didn't work, I don't know why?

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
