### ISSUE TITLE
Is Google's new paper helpful to improve the strength of AQ?

### ISSUE THREAD

**Issue by gogoai** [ymgaq/AQ#27]
The paper introduces AlphaGo Zero, the latest evolution of AlphaGo, the first computer program to defeat a world champion at the ancient Chinese game of Go. Zero is even more powerful and is arguably the strongest Go player in history.
Previous versions of AlphaGo initially trained on thousands of human amateur and professional games to learn how to play Go. AlphaGo Zero skips this step and learns to play simply by playing games against itself, starting from completely random play. In doing so, it quickly surpassed human level of play and defeated the previously published champion-defeating version of AlphaGo by 100 games to 0.

**Comment by ymgaq** [comment]
In the paper, they describes the training amount for the final version as

> Over the course of training, 29 million games of self-play were gener­ated. 

The method is too heavy to deal with a normal GPU.
From my experience, the network in the paper takes about 4 msec for each position with my machine (i.e. GTX 1080).

Therefore, even if the average move count of self-play games is 250, it takes
```
29,000,000[games] * 250[positions] * 1600[playouts] * 0.004[sec]
= 46,400,000,000[sec] = 1471[year]
```
If you wait 1500 years, I will develop it.

**Comment by gogoai** [comment]
I always thought the new paper had advanced methods,
I see, thank you

**Comment by aTan-aka-Xellos** [comment]
@ymgaq is it realistik to build and use some distributed resources provided by go community? 
It achived AlphaGo Lee lvl in 3 days, so it kinda 150 years on usual GPU?)
If involve 100+ people to contribute their PC time... or I just dreaming and it basically impossible to achive? :) 

P.S. what is your opinion of influence of this paper to existing/coming soon bots strength? 
(Especially for avaliable for public, not like FineArt which has resources but not public)

Thank you.

**Comment by higherdim** [comment]
Leela Zero has done an excellent work using distributed computing resources. That should be a good way to overcome the heavy resource problem.

**Comment by ymgaq** [comment]
I agree with you, and am looking forward to the success of the LeelaZero project.
