### ISSUE TITLE
Wrong seki detection by IsSeki()

### ISSUE THREAD

**Issue by geovens** [ymgaq/AQ#29]
I noticed a situation that AQ wrongly recognizes as seki.
![2017-10-20 21-07-07](https://user-images.githubusercontent.com/9478369/31822238-a7f58298-b5da-11e7-8d9d-4c25e73ff329.jpg)
Obviously black is dead, but IsSeki() recognizes D3 and E2 as seki.

This has great impact on rollout. Because in rollout, either by PlayoutLGR or PlayoutRandom(), a detected seki point will never be filled, so AQ will never realize that black is dead, outputing incorrect result.

**Comment by ymgaq** [comment]
Thank you for reporting.
It is a bug due to `IsSelfAtariNakade()` recognizing stones with size > 2.
I will fix it on next version.

**Comment by ymgaq** [comment]
This bug will be fixed with the new version that will be released soon.
