### ISSUE TITLE
AQ collapses when it starts playing

### ISSUE THREAD

**Issue by ryanzao1105** [ymgaq/AQ#3]
AQ can be attached by GoGui but always collapses when it plays a move. Here is the GTP shell's info

genmove w
thinking...
AQ: malloc.c:2405: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Besides, CUDA 9.0& JAVA 8.0 have been installed correctly in my PC.

**Comment by GenjiWu** [comment]
Seem that the CUDNN version must be 5.1

**Comment by ryanzao1105** [comment]
@GenjiWu  the author said AQ needed "cuda6.0/cndnn5.1".  i thinks it means cuda6.0 or cudnn5.1. 
are you testing aq all well?

**Comment by ryanzao1105** [comment]
@ymgaq  how to fix the problem ？

**Comment by ymgaq** [comment]
As already mentioned, you need install both CUDA8.0 and cudnn5.1.
