### ISSUE TITLE
Doesn't work on all PC without modern video cards

### ISSUE THREAD

**Issue by GD-fix** [ymgaq/AQ#30]
Linux all.
On all PC without video cards with support of last CUDA versions AQ doesn't work.

Is it possible to make AQ Linux release compatible with most PCs?

Thanks in advance.

**Comment by ymgaq** [comment]
You can build CPU-only version from the source code with bazel. (Use CPU_ONLY flag)
I will consider to release the CPU-only one for linux in the future version.

**Comment by GD-fix** [comment]
Unfortunately, bazel is available [only for latest distributions](url=https://software.opensuse.org/package/bazel?search_term=bazel). Most likely, it will necessary for most users to wait for the next release... How soon it is planned?

Thanks in advance.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.

**Comment by GD-fix** [comment]
What archive file of new (2.1.1) release it is necessary to download to get CPU only version for Linux?

Thanks in advance.
