### ISSUE TITLE
The  bug...

### ISSUE THREAD

**Issue by damonmaster** [ymgaq/AQ#31]
(;FF[4]CA[UTF-8]AP[GoGui:1.4.5]
KM[7.5]RE[B+Resign]
;B[cd];W[pp];B[dq];W[pd];B[ec];W[do];B[co];W[cn];B[cp];W[ce]
;B[de];W[cf];B[df];W[bd];B[cg];W[cc];B[dd];W[bg];B[bh];W[bf]
;B[ch];W[dm];B[bb];W[bc];B[cb];W[ae];B[en];W[eo];B[nc];W[qf]
;B[dn];W[dc];B[fn];W[lc];B[db];W[fc];B[fb];W[ed];B[eb];W[jq]
;B[hq];W[qn];B[nq];W[oq];B[np];W[jo];B[kp];W[jp];B[nm];W[dg]
;B[fe];W[eg];B[ff];W[dj];B[bj];W[fg];B[ei];W[di];B[dh];W[eh]
;B[fi];W[gg];B[ck];W[dk];B[cl];W[fk];B[dl];W[fd];B[hf];W[hd]
;B[he];W[id];B[hi];W[hg];B[je];W[jg];B[jf];W[jd];B[le];W[kg]
;B[ne];W[md];B[me];W[nd];B[od];W[oc];B[oe];W[pc];B[ji];W[lh]
;B[nh];W[lj];B[jl];W[ni];B[oi];W[oh];B[og];W[ph];B[mi];W[ng]
;B[nj];W[mg];B[pe];W[of];B[qe];W[rc];B[li];W[rg];B[rf];W[qg]
;B[rd];W[ld];B[rb];W[qc];B[sc];W[qb];B[nb];W[ra];B[sb];W[ob]
;B[ho];W[ih];B[ii];W[hp];B[gp];W[hr];B[gr];W[iq];B[ip];W[lp]
;B[lr];W[nn];B[po];W[on];B[op];W[pq];B[qo];W[pn];B[oo];W[mo]
;B[rq];W[qj];B[ln];W[lq];B[mr];W[io];B[mn];W[hn];B[go];W[no]
;B[lo];W[ko];B[kr];W[kq];B[ql];W[pl];B[pk];W[qk];B[mp];W[jm]
;B[ol];W[rl];B[kn];W[il];B[kl];W[ik];B[gl];W[gk];B[jn];W[in]
;B[kj];W[el];B[em];W[gn];B[fl];W[ek];B[fo];W[hl];B[gm];W[or]
;B[rn];W[rm];B[ro];W[jr];B[hs];W[is];B[gs];W[qr];B[rr];W[km]
;B[lm];W[jk];B[kk];W[nr];B[mq];W[ps];B[ns];W[ah];B[ag];W[ac]
;B[hj];W[hk];B[hb];W[hp];B[ir];W[bi];B[ai];W[ci];B[ah];W[hr]
;B[ip];W[qp];B[rp];W[hp];B[ir];W[gq];B[fq];W[hr];B[ip];W[hm]
;B[fm];W[hp];B[ir];W[cj];B[bk];W[cm];B[bm];W[hr];B[ip];W[mb]
;B[jb];W[hp];B[ir];W[bn];B[an];W[hr];B[ip];W[jc];B[kb];W[hp]
;B[ir];W[aj];B[ak];W[hr];B[gq];W[qm];B[pi];W[qi];B[pj];W[ok]
;B[nk];W[om];B[oj];W[ib];B[ia];W[hc];B[gc];W[gd];B[gb];W[ab]
;B[ba];W[ms];B[ls];W[rs];B[qq];W[sn];B[so];W[sm];B[ms];W[os]
;B[sr];W[sq];B[ss];W[ml];B[nl];W[ks];B[qs];W[bl];B[al];W[rs]
;B[js];W[bo];B[bp];W[ks];B[qs];W[ao];B[ap];W[rs];B[js];W[gi]
;B[gj];W[ks];B[qs];W[fj];B[gh];W[rs];B[js];W[ir];B[qs];W[af]
;B[aj];W[rs];B[jh];W[fh];B[hh];W[ig];B[kh];W[ks];B[qs];W[mm]
;B[im];W[rs];B[js];W[jm];B[qs];W[km];B[ll];W[rs];B[mh];W[lg]
;B[qs];W[kd];B[pr];W[ha];B[ic];W[jj];B[ib];W[ma];B[lb];W[la]
;B[ka];W[ks];B[gi];W[])

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
