### ISSUE TITLE
Instant moves late in the game

### ISSUE THREAD

**Issue by iteachcs** [ymgaq/AQ#32]
Hi,

Thank you for the nice program!  

I have a question about how AQ plays.  It seems to me that when the value goes above 90% (AQ predicts it is very likely to win), AQ will start to play instantly. It will think for a while at a certain move and then make multiple instant follow-up moves before it thinks for a while again.  I was wondering if it was a behavior by design or accidental.  The problem of this behavior is that I saw AQ made a quick but wrong move that directly ruined its winning game.  At the early stage of a game, it seems that, although AQ can sometimes make an instant move, it happens much less frequently -- AQ usually uses the full byoyomi before making a move. 

Thanks,

iteachcs

**Comment by ymgaq** [comment]
AQ skips thoughts under the following conditions for saving time.

1. When the root node is searched more than  50,0000 times.
2. When the internal winning percentage is 92% or more (or 8% or less) and the root node is searched more than 1000 times.
3 When the first candidate move is searched 100 times or more for the second candidate move.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
