### ISSUE TITLE
Problem on installing AQ with Gogui or Sabaki

### ISSUE THREAD

**Issue by tartaric** [ymgaq/AQ#33]
Hi,

I followed the instructions to install gogui on my Ubuntu 14.04 OS but it didn't work (sudo bash ./install.sh -p /usr/local -j /usr/lib/jvm/java-6-sun to execute the installation script *** I replaced by java-9 cause it's the one i'm using) but there were some errors).

Is there any other softwares than Gogui to run AQ? I tried with Sabaki but when I selected the engine of AQ in the repertory it didn't work.

Maybe I should run it on Windows? But I think on Linux it works better, can calculate more simulations because Linux uses less ressources, I am wrong? At least with Leela it works as it.

Thanks for the help.

**Comment by ymgaq** [comment]
In my environment (Ubuntu 16.04), AQ works with Sabaki.
However, Sabaki has a problem when telling stone information to the program, so AQ may not recognize correctly when called from the middle of the game record. See #20 .

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
