### ISSUE TITLE
Some question.

### ISSUE THREAD

**Issue by elpanor** [ymgaq/AQ#34]
1. When I raise up node_limit to 132109, It works fine.
But 262147failed. Is max node_limit is around 2^17?

2. When using 132109, memory usage is still about 10giga.
How can I raise up memory usage? What do I modify?

3. What,s the meaning of expand_cnt?
To expand search ,Should I go up expand_cnt ? Or go down?

Thank you.

**Comment by ymgaq** [comment]
1. It depends on your processing system and compiler. The upper limit is not set particularly on the program.
2. AQ does not use more memory than allocated with node_limit.
3. The threshold at which to expand the next node. When the number of searches exceeds expand_cnt, a child node is created.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
