### ISSUE TITLE
Is it possible to create a stronger AQ-mini?

### ISSUE THREAD

**Issue by yauwing** [ymgaq/AQ#35]
Hello,

Many friends of mine have computers with strong CPUs like i7, Ryzen or even Xeon but non-Nvidia GPU.

Is it possible to create a stronger version of AQ-mini by removing the thread = 2 only limit?

**Comment by ymgaq** [comment]
With CPU-only version, AQ uses all available CPU resources for NN evaluation. So, unless you have a multi-CPU (NOT multi-core) machine, setting thread to 2 will not get stronger.

**Comment by geovens** [comment]
Hi ymgaq. Maybe you can consider build AQ-mini with AVX-enabled TensorFlow? 

I just did a test. On my Windows computer with an i7-4790 CPU, AQ-mini (downloaded) rollouts ~9.0k times in 20 seconds for the first two moves of a game, while my AVX-enabled build rollouts ~12.5k times in 20 seconds. That were 39% more rollouts. The CPU usage was also slightly decreased from ~90% to ~85%. I built my build with https://github.com/ymgaq/AQ/archive/v2.0.3.zip and only uncommented “#define CPU_ONLY”. 

AQ-PS also got ~35% more rollouts by switching to AVX-enabled TensorFlow.

**Comment by ymgaq** [comment]
The CPU-only version is mainly for testing, I do not think about speeding up by narrowing the choices of CPU. If you need, it can be built according to [this procedure](https://joe-antognini.github.io/machine-learning/windows-tf-project).
