### ISSUE TITLE
Not sure about this IsEyeShape() value is intended or a bug

### ISSUE THREAD

**Issue by geovens** [ymgaq/AQ#36]
![2017-11-03 21-25-09](https://user-images.githubusercontent.com/9478369/32375742-aae0cd56-c0dd-11e7-8d0e-4051dc09cde0.jpg)

In this corner, IsSelfAtariNadake(S19) is true as expected. What I wonder about is the fact that IsEyeShape(S19) is true. Is this intended? If there was a black stone at T18, IsEyeShape(19) is false as it should be.  
In fact, in this corner white should play S19 to kill black, but AQ excludes S19 as a candidate child node because it is considered an eyeshape.

**Comment by ymgaq** [comment]
Your point is right.

This is not a bug but AQ specification. AQ is designed to ignore some shapes with low appearance probability for speeding up. If I try to recognize this shape as `SelfAtariNakade`, the code becomes complicated and slows down. 

Please tell me if you have a good idea to modify this.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
