### ISSUE TITLE
Which version of tensorflow did you use to compile AQ?

### ISSUE THREAD

**Issue by bjiyxo** [ymgaq/AQ#37]
I tried tensorflow 1.2 & 1.4 to compile AQ, and neither of them worked.
But I can compile the example you gave (matmul.cpp) and it works.

The following is the error message.

1>  Generating Code...
1>search.obj : error LNK2019: unresolved external symbol "public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z) referenced in function "protected: class tensorflow::NodeDef * __cdecl google::protobuf::internal::RepeatedPtrFieldBase::Mutable<class google::protobuf::RepeatedPtrField<class tensorflow::NodeDef>::TypeHandler>(int)" (??$Mutable@VTypeHandler@?$RepeatedPtrField@VNodeDef@tensorflow@@@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@IEAAPEAVNodeDef@tensorflow@@H@Z)
1>search.obj : error LNK2019: unresolved external symbol "public: __cdecl google::protobuf::internal::LogMessage::~LogMessage(void)" (??1LogMessage@internal@protobuf@google@@QEAA@XZ) referenced in function "protected: class tensorflow::NodeDef * __cdecl google::protobuf::internal::RepeatedPtrFieldBase::Mutable<class google::protobuf::RepeatedPtrField<class tensorflow::NodeDef>::TypeHandler>(int)" (??$Mutable@VTypeHandler@?$RepeatedPtrField@VNodeDef@tensorflow@@@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@IEAAPEAVNodeDef@tensorflow@@H@Z)
1>search.obj : error LNK2019: unresolved external symbol "public: class google::protobuf::internal::LogMessage & __cdecl google::protobuf::internal::LogMessage::operator<<(char const *)" (??6LogMessage@internal@protobuf@google@@QEAAAEAV0123@PEBD@Z) referenced in function "protected: class tensorflow::NodeDef * __cdecl google::protobuf::internal::RepeatedPtrFieldBase::Mutable<class google::protobuf::RepeatedPtrField<class tensorflow::NodeDef>::TypeHandler>(int)" (??$Mutable@VTypeHandler@?$RepeatedPtrField@VNodeDef@tensorflow@@@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@IEAAPEAVNodeDef@tensorflow@@H@Z)
1>search.obj : error LNK2019: unresolved external symbol "public: void __cdecl google::protobuf::internal::LogFinisher::operator=(class google::protobuf::internal::LogMessage &)" (??4LogFinisher@internal@protobuf@google@@QEAAXAEAVLogMessage@123@@Z) referenced in function "protected: class tensorflow::NodeDef * __cdecl google::protobuf::internal::RepeatedPtrFieldBase::Mutable<class google::protobuf::RepeatedPtrField<class tensorflow::NodeDef>::TypeHandler>(int)" (??$Mutable@VTypeHandler@?$RepeatedPtrField@VNodeDef@tensorflow@@@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@IEAAPEAVNodeDef@tensorflow@@H@Z)
1>search.obj : error LNK2019: unresolved external symbol "private: void __cdecl google::protobuf::Arena::AddListNode(void *,void (__cdecl*)(void *))" (?AddListNode@Arena@protobuf@google@@AEAAXPEAXP6AX0@Z@Z) referenced in function "public: void __cdecl google::protobuf::Arena::Own<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (??$Own@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Arena@protobuf@google@@QEAAXPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>search.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
1>D:\AQ2031\win\x64\Release\aqgo.exe : fatal error LNK1120: 6 unresolved externals
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

I think it is owing to the tensorflow version, so which version of tensorflow did you use to compile AQ?

**Comment by arena** [comment]
FYI: your code has local variables and since you didn't format it as code those were interpreted as @ at messages to GitHub users. Please edit your issue and format `the code `

(I've unfollowed this)

**Comment by geovens** [comment]
I build AQ-PS using tensorflow 1.3.1 & visual studio 2015 with no problem. Not sure whether your problem is related to tensorflow version though.

**Comment by bjiyxo** [comment]
Thx for reply. I used tensorflow.lib + tensorflow.dll to compile both the example(matmul.cpp) and AQ. I'm trying tensorflow 1.3.1 now.

**Comment by bjiyxo** [comment]
I tried tensorflow 1.3.1, and got the following message,

1>  nueral_net.cc 

1>  pattern3x3.cc 

1>  playout.cc 

1>  print.cc 

1>  search.cc 

1>  sgf.cc 

1>..\src\sgf.cc 

(442): error C2664: 'HANDLE FindFirstFileW(LPCWSTR,LPWIN32_FIND_DATAW)': cannot convert argument 1 from 'const char *' to 'LPCWSTR'
1>  ..\src\sgf.cc 

(442): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>..\src\sgf.cc 

(458): error C2440: 'initializing': cannot convert from 'WCHAR [260]' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>  ..\src\sgf.cc 

(458): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>  zobrist.cc 

1>  Generating Code...
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

I am trying to figure out what happened.

**Comment by geovens** [comment]
You can first try to change the setting in project properties -> configuration properties -> general -> character set from unicode or multi-byte to "not set"...
