### ISSUE TITLE
why did you delete my issue?

### ISSUE THREAD

**Issue by ryanzao1105** [ymgaq/AQ#4]
the problem exists, how to fix it?

**Comment by ymgaq** [comment]
It is closed but not deleted. Refer https://github.com/ymgaq/AQ/issues/3
You need install both of CUDA-8.0 (not 9.0) and cudnn-5.1 for running AQ as described in Requirement.

In addition, I recommend using a machine with 4 GB or more memory because AQ consumes a lot of memory.

**Comment by ryanzao1105** [comment]
@ymgaq  tensorflow requires cudnn6.0, is that true?

**Comment by ymgaq** [comment]
Latest tensorflow requires cudnn 6.0, but AQ requires cudnn 5.1 because it is build with an old version.

**Comment by ryanzao1105** [comment]
@ymgaq so, are you still developing aq? will there be higher and stronger version released?

**Comment by ryanzao1105** [comment]
@ymgaq and have you tested it with Leela, another Go AI from Belgium, can aq win Leela with the same hardware?

**Comment by ymgaq** [comment]
Still developing.

I am testing AQ on Computer Go Server (CGOS). http://www.yss-aya.com/cgos/19x19/standings.html
The hardware configuration of AQ-2.0.3 (develop ver., NOT released one) is corresponding to 8t1g or 4c1g (i7 6700K + GTX 1080), but I don't know about that of other programs.

Of course, anyone is free to test AQ with other programs directly.

**Comment by ryanzao1105** [comment]
@ymgaq 
1)Does AQ have the function of ponder?  if yes , how to switch it on and off?
2)are you still going on developing aq? will there be higher and stronger version released?

**Comment by ymgaq** [comment]
1) It is the default specification and can not be turned off.
I will consider whether to be able to change by option in a future version.

2) Still developing and will release new versions.

**Comment by ryanzao1105** [comment]
@ymgaq i have found some bugs, and suggestions.
1) aq doesn't recognize some kind of life-death situation, it happens that dragon gets captured.
2)aq doesn't know how to simplize the game when it has good advantage, sometimes gets into a complecated situation where the advantage gets turned over and it finally loses the game.
1) wish aq to use less time when the move has only one choice.
2)wish aq to have an analysis mode

**Comment by ymgaq** [comment]
They are not bug but specification. AQ is not a perfect player.
Anyone is free to develop AQ as you wish, because AQ is the open source project.
