### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by jinp65** [ymgaq/AQ#44]
Hi ymgaq,
I try to build the AQ, system is ubuntu 16.04, bazel config with cuda, cuda 8.0 cudnn 6.0, seems the final link failed, 
the way I do it is: copy AQ-master into tensorflow-master/tensorflow/examples/ dir, then run
./configure
bazel build /tensorflow/examples/AQ-master/...
in tensorflow-master dir

Thanks.
 following are the last couple lines of output:

validate.cc:(.text._ZN10tensorflow5graph16ValidateGraphDefERKNS_8GraphDefERKNS_19OpRegistryInterfaceE+0x92): undefined reference to `tensorflow::ValidateNodeDef(tensorflow::NodeDef const&, tensorflow::OpDef const&)'
validate.cc:(.text._ZN10tensorflow5graph16ValidateGraphDefERKNS_8GraphDefERKNS_19OpRegistryInterfaceE+0xaa): undefined reference to `tensorflow::CheckOpDeprecation(tensorflow::OpDef const&, int)'
bazel-out/local_linux-opt/bin/tensorflow/core/util/tensor_bundle/libnaming.a(naming.o): In function `tensorflow::MetaFilename[abi:cxx11](tensorflow::StringPiece)':
naming.cc:(.text._ZN10tensorflow12MetaFilenameB5cxx11ENS_11StringPieceE+0x19): undefined reference to `tensorflow::strings::Printf[abi:cxx11](char const*, ...)'
bazel-out/local_linux-opt/bin/tensorflow/core/util/tensor_bundle/libnaming.a(naming.o): In function `tensorflow::DataFilename[abi:cxx11](tensorflow::StringPiece, int, int)':
naming.cc:(.text._ZN10tensorflow12DataFilenameB5cxx11ENS_11StringPieceEii+0x1f): undefined reference to `tensorflow::strings::Printf[abi:cxx11](char const*, ...)'
collect2: error: ld returned 1 exit status
Target //tensorflow/examples/AQ-master/src:AQ failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6393.312s, Critical Path: 911.08s
FAILED: Build did NOT complete successfully

**Comment by ymgaq** [comment]
If you are using the latest tensorflow, ```--config=monolithic --config=cuda``` may help you when building with bazel.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
