### ISSUE TITLE
My bot (AQ_vg)  is often losing on time at CGOS

### ISSUE THREAD

**Issue by Vargooo** [ymgaq/AQ#46]
Hello !
Is there a way to make AQ go into emergency mode when there's 60 seconds left (instead of 15 sec.) I think it would solve my problem.
I have a much better computer than before, but my bot is losing more and more Elo points on CGOS , because of the losses on time, (and probably bad configuration, too)
My Internet connexion is average.
Thanks for this beautiful program !

![lose](https://user-images.githubusercontent.com/33191125/34571222-3a765e48-f16e-11e7-8a6a-a1bacb9fe1d3.jpg)

**Comment by elpanor** [comment]
In source code there is emergency time set.
That is 15sec. You can change to 60sec.

**Comment by Vargooo** [comment]
Ah... OK.
I'll try to dig into the code, but I'm afraid it will be a bit too much for me . Thx anyway.

**Comment by ymgaq** [comment]
In the next version (just in preparation) I will consider whether to allow users to modify emergency time from the config file.

**Comment by Vargooo** [comment]
That would be perfect. I can't wait for the next version !
The config file is an excellent idea, it's user friendly.

**Comment by ymgaq** [comment]
Added emergency time setting in [v2.1.1](https://github.com/ymgaq/AQ/releases).

**Comment by Vargooo** [comment]
Thank you for the command -emergency time !

I was wrong, even with -emergency time[sec] =200 (!)  my bot had 8 losses on time in 108 games...
At the beginning of the emergency time, it takes easily 4-6 sec/move.  Near the end of its time, when there's only 10s left or so, it takes around 1s/move.  (I have a connexion via smartphone)

But your AQ is so strong, that it reached good BayesElo.  
[AQ211_vg ](http://www.yss-aya.com/cgos/19x19/bayes.html)
