### ISSUE TITLE
Is the reinforced learning like AlphaGo successed?

### ISSUE THREAD

**Issue by jwhur72** [ymgaq/AQ#5]
Regards...

**Comment by ymgaq** [comment]
You mean the method described in the Nature paper?
I think most of the strong programs are adopting that method to generate the value network.

**Comment by jwhur72** [comment]
Yes I know...
But as I know, the ray isn't adopted yet.
I would like to know about AQ.

Regards...

**Comment by ymgaq** [comment]
AQ adopts the method.
Please wait until the learning part is released to know the detail.

**Comment by jwhur72** [comment]
Thanks...
