### ISSUE TITLE
The Go program terminated unexpectedly

### ISSUE THREAD

**Issue by suzimoon** [ymgaq/AQ#51]
When I was trying to run AQ on GoGui,
After I ran the New Program, an error message popped up stating: 

"The Go program did not respond to any commands. One possible reason is that the command for executing the program in GTP mode was not correct."

what should I do?

**Comment by ymgaq** [comment]
First of all, you should choose "Wait" several times when the error dialog comes out.

If the problem is not solved, you can test with AQ in `self match` mode.
Set `self match` flag to be `on` in 'aq_config.txt.' 

Then in command prompt, type
```
> cd (install directory)   
(ex. C:\Users\%USERNAME%\AQ)
> AQ.exe
```
Then you may find what is wrong.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
