### ISSUE TITLE
When is AQ 2.1.1 going to be released for Windows?

### ISSUE THREAD

**Issue by jillybob** [ymgaq/AQ#52]
I have seen some impressive results from the [new AQ version](http://www.yss-aya.com/cgos/19x19/cross/AQ-2.1.1-4t1g.html). Just wondering if I can get the Windows binary.

Thank you.

**Comment by Vargooo** [comment]
Yes, very impressive... I can't wait to get the Windows binaries for this version.
What kind of hardware did you use, to obtain these results on CGOS ?

Thank you !

**Comment by ymgaq** [comment]
I hope it will be released soon.
The hardware was i7-6700(4 thread)/GTX1080(1 gpu).
