### ISSUE TITLE
When will you release a new version of AQ？

### ISSUE THREAD

**Issue by lige74** [ymgaq/AQ#54]

**Comment by Heiseikiseki** [comment]
私も気になります。ですが気を長くして待ちましょう。

**Comment by ymgaq** [comment]
Duplicate with #49 and #52.
I hope it will be released soon.

**Comment by higherdim** [comment]
I've tried AQ on Tencent Wildfox go. It reached strong 9d with very impressive performance. Looking forward to the new release!

**Comment by ymgaq** [comment]
It was [released](https://github.com/ymgaq/AQ/releases).
