### ISSUE TITLE
CGOS config

### ISSUE THREAD

**Issue by Vargooo** [ymgaq/AQ#55]
Hello,
I run the bot AQ_vg, and I have a new computer. 

CPU : i9-7920X  (12 cores- 24 threads)
GPU : 2x GeForceGTX 1080 Ti
RAM : 64 GB
Windows 10

AQ_vg should get a good Elo at CGOS, but I think I have bad config...
My config.txt and aq_config.txt are below.
What should I change ? (particularly not sure about : priority 9, lagbuffer 100, -thread count =8)

Thank you once again for this beautiful program.
Like everyone else, I can't wait to have the new version !

 config file
 Bot name must be within 18 characters.
 Port is 6809 in 9x9, 6819 in 19x19.

%section server
    server yss-aya.com
    port 6819

%section player
     name      AQ_vg
     password  .......
     invoke    AQ.exe --gtp --lagbuffer 100 --quiet
     priority 9

 Hardware setting 
 Set number of 1-8 for 'gpu count'.
 'thread count' is number of the total usable threads.
-gpu count =2
-thread count =8

 Time contorol setting 
 If using 'time_left' command via GTP,
set 'time controll' to 'off'.
-main time[sec] =900
-byoyomi[sec] =0
-time controll =off

 Thinking setting
-japanese rule =off
-komi =7.5
-symmetrical index =0
-mimic go =off
-never resign =off

 Others 
-self match =off
-save log =on
-master =off
-worker =off
-pb path =pb
-resume sgf path =
-worker count =1
-use pondering =on

**Comment by ymgaq** [comment]
See the [latest version description](https://github.com/ymgaq/AQ/blob/master/README.md). 
The recommended settings are as follows.
```
-main time[sec] =900  
-byoyomi[sec] =0  
-emergency time[sec] =15 #set 60 when connecting from outside Japan  
```

**Comment by Vargooo** [comment]
Superb, thank you !
