### ISSUE TITLE
AQ resigns immediately on handicap games

### ISSUE THREAD

**Issue by 2ji3150** [ymgaq/AQ#57]
SabakiでAQと対戦する時置石が多いだとAQは最初から投了します。コンフィグファイルで-never resign =onにしても変わらず。

**Comment by ymgaq** [comment]
Since AQ was trained with no handicap stone, if many handicap stones are placed, winning percentage will be less than 10% and it will resign. In the next minor update, I will set it so that it never resign until the 128th move on handicap games.

**Comment by Heiseikiseki** [comment]
Got it. Can you update the cudnn dll to the cudnn64_7.dll in the next minor update,too?

**Comment by ymgaq** [comment]
Currently, TensorFlow1.4 does not officially support cuda9/cudnn7. Especially on Windows, there is no way to build a binary with the latest version of cuda. You can try to build by yourself.

**Comment by Heiseikiseki** [comment]
I have checked the TensorFlow doc. Seems It will support CUDA9 and cuDNN7 on ver 1.5 which now is on 1.5.0-rc1. Maybe I will notice you when the regular version is out. I would also want to try to build , but it it is a little hard for me.  I wonder if you have free time you can write a step by step build document in japanese.

**Comment by ymgaq** [comment]
Yes, TensorFlow1.5 supports CUDA9/cuDNN7 for usual learning. However, you need to build a binary file with CMake for Windows.  There is only [this information](https://github.com/tensorflow/tensorflow/tree/r1.5/tensorflow/contrib/cmake) to build on Windows even for v1.5.

In order to correspond to CUDA9, I think you need to make many code modifications in TensorFlow. I can not give any useful advice on that.

**Comment by Heiseikiseki** [comment]
OK， if that is not too hard I will give a try. Thanks. BTW, is AQ trained by Japanese rule? I saw the config file has -japanese rule and komi . Does this option affect AQ's play style?  Does AQ use the dynamic komi? Or just for calculate  win or lose? Sorry I know it's out of this topic. If needed I will open new issue.

**Comment by yauwing** [comment]
Current version of AQ can be make to play at higher handicap without surrendering immediately by setting the initial komi to a higher value - I use 7 x handicapped stones, I would reduce the komi if AQ ever catches up by checking if the roll % is increasing to higher than 50%.

If use GoGui, komi can be changed numerous times during the game by just send gtp command in the shell window such as
komi 35  and eventually lower it back to komi 0.5

This dynamic komi method may be better than forcing AQ not to consider resigning until 128 moves?
If black manages to kill a big white group early in the game that even a big komi would indicate less than 10% of winning chance for white then white should resign - just like human would do.

**Comment by pcengine** [comment]
@ymgaq  

>Since AQ was trained with no handicap stone, if many handicap stones are placed, winning percentage will be less than 10% and then it will resign. In the next minor update, I will set it not to resign until the 128th move on handicap  games. 

Could you please tell us when will you release the next minor update? Also, I have tried "never resign =on", but AQ didn't play moves, it just kept passing and passing.

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
