### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by Tim2018** [ymgaq/AQ#58]
genmove b
undo
play  b D17
AQ 2.1.1 will  crash，but AQ2.0.3 is ok！

**Comment by pnprog** [comment]
Yes, I can confirm this bug (https://github.com/pnprog/goreviewpartner/issues/15).

**Comment by jfsamper** [comment]
I can confirm this issue as well (using AQ-mini 2.1.1 binary)

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
