### ISSUE TITLE
How to use "emergency time setting" ?

### ISSUE THREAD

**Issue by txhylh** [ymgaq/AQ#59]
New AQ is very strong, thank you! but I don't know how to use "emergency time setting" .

**Comment by ymgaq** [comment]
The `emergency time[sec]` is the time setting to immediately return moves to avoid losing when the 'sudden death' time setting. Usually, you don't need to change the setting. By default, when the remaining time is 15 seconds or less and there is no byoyomi time, AQ returns a move within 0.1 seconds without thinking.

**Comment by txhylh** [comment]
Thank you!
