### ISSUE TITLE
I have a one question.

### ISSUE THREAD

**Issue by 22nsuk** [ymgaq/AQ#6]
Do you have a any plan about build your AI using OpenCL?
I heard that you can build the OpenCL version using tensorflow-cl.
I hope that the OpenCL version will be distributed with the Windows version.
Thx.

**Comment by ymgaq** [comment]
I have no plan to develop with OpenCL, but am preparing for the Windows version with CUDA. 
Of course, anyone is free to develop AQ using OpenCL.
