### ISSUE TITLE
strange crash

### ISSUE THREAD

**Issue by Vargooo** [ymgaq/AQ#60]
Hello,
The new version is very strong.
my bot (AQ211_vg , playing White) had a problem during game 361313.
Black's time seemed incoherent at times, and in the end, my bot crashed with the following message : 

![cgos](https://user-images.githubusercontent.com/33191125/35262463-230be0a6-0015-11e8-8180-58c80f990a5c.jpg)

I'm very happy with this new version nonetheless.

**Comment by ymgaq** [comment]
AQ sent her move "C15" correctly. It was not caused by AQ but your CGOS client. I cannot support you on this error.

**Comment by Vargooo** [comment]
OK thank you.
