### ISSUE TITLE
it stuck at beginning when AQ2.0.3 plays against AQ2.1.1  on  sabaki

### ISSUE THREAD

**Issue by zxo102** [ymgaq/AQ#61]
Hi ymgaq,
  On my windows 10 (GPU GTX1060, i7 7th gen),  I tried to let AQ2.0.3 to play against AQ2.1.1  on  sabaki with their default aq_default files but it stuck at very beginning and no move at all.  I set them up with "Engines"-->"Manage Engines..." and "Attach...".  Those two version of AQs are in different directories.

Are there any suggestions?

B.S. Thanks for your AQ2.1.1.

zxo10

**Comment by ymgaq** [comment]
Since AQ occupies all of the GPU memory, at least 2 GPUs are necessary for your purpose. If you have them, use launch commands of `CUDA_VISIBLE_DEVICES=0 ./AQ.exe` and `CUDA_VISIBLE_DEVICES=1 ./AQ.exe` for each version.

**Comment by zxo102** [comment]
got u. Thanks a lot.
