### ISSUE TITLE
How to know whether the parameters are set best ?

### ISSUE THREAD

**Issue by txhylh** [ymgaq/AQ#63]
First of all, thank you for bringing us a powerful go program!
When setting parameters, how to know "-thread coun = 4" on my computer is the best or no ? and set "-use pondering =on" or off ? What difference between the two ?
Thank you !

**Comment by ymgaq** [comment]
If `use pondering` is on, AQ doesn't stop thinking even at the opponent's turn, so I recommend you leave it as it is.

For `thread count`, you can judge by looking at log information as follows.

```
total games=36865, evaluated policy=1669(1), value=8165(193)
|move|count  |value|roll |prob |depth| best sequence
|D16 |  19215| 51.6| 45.7| 21.9|   17| D16->Q4 ->C4 ->Q16->F3 ->C10->O17->R14
```

You can find the number of unprocessed 'value network' =193 in `value=8165(193)`, which AQ did not evaluate it in time. Usually, AQ stops thinking of CPU threads when unprocessed 'value network' exceeds 192.

If these numbers are often less than 192, you can increase `thread count`.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
