### ISSUE TITLE
question about the settings-symmetrical index and mimic go

### ISSUE THREAD

**Issue by Matuiss2** [ymgaq/AQ#64]
<!--
Thank you for reporting issues.
Since the developer is so busy, please understand that unimportant questions or requests may not be responded.

[Before adding an issue]
Please search and check if there are similar issues and questions, including those already closed.

[How to add a new issue]
**Title**
Make it possible to grasp the content of the issue by title only.

  Good: 'Resigns immediately on handicap games'
  Bad: 'some questions', 'a bug'

**Comments**
Please write the contents concisely.
Do not include multiple topics in one issue.

In the case of a bug, please describe the following contents.
+ Execution environment (AQ ver. / OS / CPU / GPU)
+ Reproduction procedure (in detail as much as possible)
+ How to fix it (if you have an idea)

**Labels** (able to attach from the right setting list)
'question': just a question
'enhancement': request for additional functions and improvement
'bug': a bug

Other labels will be judged by the developer, so the reporter should not use it.
--!>
What does this setting do?

**Comment by ymgaq** [comment]
`-gpu count =1` number of GPUs
`-thread count =4` number of total CPU threads

`-main time[sec] =0` main time
`-byoyomi[sec] =5` Byoyomi time
`-emergency time[sec] =15` remaining time limit for no thinking moves. AQ will return a move very quickly when left time is less than this value and there is no Byoyomi.

`-japanese rule =off` Japanese rule or Chinese rule
`-komi =7.5` Komi
`-symmetrical index =8` board symmetry considered by AQ. 0 => as it is, ... 8 => random rotation. Do not change.
`-use pondering =on` AQ continues to think during the opponent's turn if `on`
`-mimic go =off` AQ plays mimic go if `on` when it is white.
`-never resign =off` AQ never resign if `on`. (send pass if the winning percentage < 10 %)

`-self match =off` go to self-match mode for debug if `on`. Output log to the error console and txt file.
`-save log =on` save the thinking log and sgf files in ./log/ if `on`.
`-pb path =pb` directory path of .pb file.
`-resume sgf path =` file path of resuming sgf file.

`-master =off` launch as master node of cluster. Do not change if you use single machine.
`-worker =off` launch as worker node of cluster. Do not change if you use single machine.
`-worker count =1` number of worker node of cluster. Do not change if you use single machine.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
