### ISSUE TITLE
How to time setting in CGOS?

### ISSUE THREAD

**Issue by ringworld3702** [ymgaq/AQ#65]
I'd like to set a byoyomi of 0.5 seconds in CGOS. 
However, it always begins with a main time of 900 seconds.
How do I fix it?
I want to see how many points AQ can get by playing fast.

**Comment by ymgaq** [comment]
First of all, you should read [description](https://github.com/ymgaq/AQ#time-control-on-cgos)  for CGOS time settings. It is not recommended (but not forbidden) that users test AQ as it is on CGOS (i.e. no source code improvement).

If you want to do that, you need to modify behavior of `time_left` command in [gtp.cpp](https://github.com/ymgaq/AQ/blob/master/src/gtp.cpp#L224) and build it.

**Comment by ringworld3702** [comment]
I just wanted to check how many points AQ scored when they played the game without time. Thanks for your reply.
