### ISSUE TITLE
enhancement: add a command line parameter to indicate another aq_config.txt

### ISSUE THREAD

**Issue by pnprog** [ymgaq/AQ#67]
Hi!

It would be nice to be able to tell AQ to use another **aq_config.txt** file directly from the command line.

For exemple:
```
AQ.exe --config fast_game.txt #this fast_game.txt file would define the byoyomi at 5s
AQ.exe --config slow_game.txt #this slow_game.txt file would define the byoyomi at 120s
AQ.exe --config tournament.txt #this tournament.txt file would turn pondering off to let the other bot use the computer full
AQ.exe #without parameter, AQ falls back to the usual aq_config.txt file
```

It would be better to be able to change all AQ parameters from the command line, but as an intermediate measure, this should be easy enough to implement. Even the **--config** flag is not really necessary if you other flags are to be used, ie `AQ.exe slow_game.txt`

**Comment by ymgaq** [comment]
AQ exactly has this command line option. Use `--config=<file path>`.
Note that it must be specified as full path if working directory is not set. (e.g. `AQ.exe --config=C:\Users\user\AQ\aq_config_another.txt`)

**Comment by pnprog** [comment]
Haha!
Sorry I missed that!
