### ISSUE TITLE
Segmentation fault after compiling from source in Linux

### ISSUE THREAD

**Issue by MatthewZalesak** [ymgaq/AQ#68]
I have a Linux system that does not have a GPU so I tried compiling AQ from source (Fedora 27 64 bit if it helps).  The only instruction provided is "see [this instruction](https://medium.com/jim-fleming/loading-a-tensorflow-graph-with-the-c-api-4caaff88463f)" which is a link to a website that compiles a C++ program with Tensorflow.

This is my best guess on how to use those instructions to build AQ (after some trial and error):

1. `cd /opt`
1. `git clone --recursive https://github.com/tensorflow/tensorflow`
2. `git clone https://github.com/ymgaq/AQ`
3. `ln -s /opt/AQ /opt/tensorflow/tensorflow/AQ`
4. `cd /opt/tensorflow`
5. `./config`
6. `cd /opt/tensorflow/tensorflow/AQ/src`
7. `bazel build :AQ --config=monolithic`
9. `cp /opt/tensorflow/bazel-bin/tensorflow/AQ/src/AQ /opt/AQ/AQ`
10. `cp /opt/AQ/prob/* /opt/AQ/`

Next, for the sake of testing I modify aq_config.txt to say "- self match =on".  When I run the command `./AQ` I get a segmentation fault.

```
configuration loaded.
2018-01-27 20:36:36.306768: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
Segmentation fault (core dumped)
```
I am not sure how to resolve this issue since the `bazel build` step finished without error.  Perhaps someone can see a problem with the way I compiled it?

I suspect that the problem is that I am missing a step somewhere but I am not sure since there is no list of steps for me to compare with.  It could be a separate issue but I think it would be very useful to have a precise set of steps for compiling and setting up AQ so that people unfamiliar with the Tensorflow can figure out how to compile it.

Thanks in advance, I look forward to trying out AQ.

**Comment by ymgaq** [comment]
I have not actually built without a GPU, but your procedure looks perfect.

Did you add `#define CPU_ONLY` in [search.h](https://github.com/ymgaq/AQ/blob/850bcff9b129ccfafa74e1a3a86fdb88de31471f/src/search.h#L18)? If `CPU_ONLY` is not defined, AQ will try to get GPU devices and cause a segmentation fault.

**Comment by MatthewZalesak** [comment]
I missed that option.  I uncommented the line and now the compiling works fine.  Thank you very much!
