### ISSUE TITLE
Endgame theory

### ISSUE THREAD

**Issue by elpanor** [ymgaq/AQ#70]
<!--
Thank you for reporting issues.
Since the developer is so busy, please understand that unimportant questions or requests may not be responded.

[Before adding an issue]
Please search and check if there are similar issues and questions, including those already closed.

[How to add a new issue]
**Title**
Make it possible to grasp the content of the issue by title only.

  Good: 'Resigns immediately on handicap games'
  Bad: 'some questions', 'a bug'

**Comments**
Please write the contents concisely.
Do not include multiple topics in one issue.

In the case of a bug, please describe the following contents.
+ Execution environment (AQ ver. / OS / CPU / GPU)
+ Reproduction procedure (in detail as much as possible)
+ How to fix it (if you have an idea)

**Labels** (able to attach from the right setting list)
'question': just a question
'enhancement': request for additional functions and improvement
'bug': a bug

Other labels will be judged by the developer, so the reporter should not use it.
--!>

**Comment by elpanor** [comment]
1. In end game ..sente and gote is important
But Ai don recognize sente and gote.

Ex) after move_cnt 200, compare candidate 1 2 3
Candidate 1 a3 a4 b3 b4
Candidate 2 b3 b4 a3 a4
Candidate 3 .......
Then i choose candidate 2 and compare win_rate 
(a3 a4 b3 b4 //// b3 b4 a3 a4)
If b3 b4 a3 a4 win_rate is higher than candidate1 sequence ..then candidate 2 was sente.

**Comment by elpanor** [comment]
This methods may cause speed down.

2. 2.11 has bug(??)  for all shapes.
They recognize not only empty vertex but also placed stone for eyeshape falseeye selfatari and so on.
Is it intended?

**Comment by elpanor** [comment]
3. 2.11 has still don recognize some shapes(ex flowe five ) so i am checking for unusual types with making that types in tree search.
If it is difficult to check most types I think Aq needs to make special unusual cheking system.

**Comment by elpanor** [comment]
4. I don know it is possible.
Aq has errors in 1line and corner Nakade & vital.
I think separate nakade & vital point in mid position with 1line and corner position.
Corner position vital point is much different in mid position.

**Comment by elpanor** [comment]
4.. ex) in mid position straight six is alive type. But in corner much more complex.

**Comment by ymgaq** [comment]
AQ is open source software, anyone can participate in development. If you feel that you can make AQ stronger, implement it, build it, measure the rating difference with the current version, and send a pull request.

**Comment by trainewbie** [comment]
Hi, elpanor. I'm sorry to have a question not related to this article.
Did you build AQ on windows? Which version of tensorflow did you use for building it on VS2015?

**Comment by ymgaq** [comment]
@trainewbie  I built it with [contrib/cmake](https://github.com/tensorflow/tensorflow/tree/r0.12/tensorflow/contrib/cmake) in TensorFlow r0.12. I think later versions (r1.3 or r1.4) may also work.

**Comment by trainewbie** [comment]
@ymgaq Thanks for your kind answer 👍 :)

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
