### ISSUE TITLE
CPU only version of new release label:question

### ISSUE THREAD

**Issue by GD-fix** [ymgaq/AQ#71]
What archive file of new (2.1.1) release it is necessary to download to get CPU only version for Linux?

Thanks in advance. #

**Comment by ymgaq** [comment]
There is no released files for Linux/CPU-only. You can build it by using Bazel. See #68.

**Comment by GD-fix** [comment]
Unfortunately, bazel is available only for latest distributions. Most likely, it will necessary for most users to wait for the  CPU only release...

**Comment by ymgaq** [comment]
You can prepare the latest Linux, for example by borrowing a server. Because building new environment for tensorflow takes time, there is no plan to release for Linux at the moment.

**Comment by GD-fix** [comment]
I had downloaded and installed bazel 0.7.0-6.1.
After executing:
bazel --output_user_root=/home/INSTall/0Go/AQ-2.1.1 build ...
I have got subfolder 'install', where are next files:
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/embedded_tools
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/A-server.jar
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/build-runfiles
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/install_base_key
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/java.version
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/jdk.BUILD
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/libunix.so
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/linux-sandbox
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/process-wrapper
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/xcode-locator

What file is the AQ run?
