### ISSUE TITLE
A new way to produce stronger weight?

### ISSUE THREAD

**Issue by higherdim** [ymgaq/AQ#74]
https://github.com/gcp/leela-zero/issues/814

Looks like the LZ folks found a simple but effective way to improve the strength. 
Wondering if the same can be done to AQ given a few best weights, and incorporate the technic to further training. 

<!--
Thank you for reporting issues.
Since the developer is so busy, please understand that unimportant questions or requests may not be responded.

[Before adding an issue]
Please search and check if there are similar issues and questions, including those already closed.

[How to add a new issue]
**Title**
Make it possible to grasp the content of the issue by title only.

  Good: 'Resigns immediately on handicap games'
  Bad: 'some questions', 'a bug'

**Comments**
Please write the contents concisely.
Do not include multiple topics in one issue.

In the case of a bug, please describe the following contents.
+ Execution environment (AQ ver. / OS / CPU / GPU)
+ Reproduction procedure (in detail as much as possible)
+ How to fix it (if you have an idea)

**Labels** (able to attach from the right setting list)
'question': just a question
'enhancement': request for additional functions and improvement
'bug': a bug

Other labels will be judged by the developer, so the reporter should not use it.
--!>

**Comment by ymgaq** [comment]
Probably it is a technique called "Chimera" which is well known in other game algorithms such as Shogi. Chimera often overcomes the original parameters, but in the long run it may be weak against other programs and it may seriously hinder growth.

**Comment by higherdim** [comment]
Ok. That makes sense to not use it if it hurts in the long run.

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
