### ISSUE TITLE
Violate of GTP protocol

### ISSUE THREAD

**Issue by bixbyr** [ymgaq/AQ#76]
The GTP protocol version should be sent as "2" not "2.0". Although some clients may understand this, others such as gomill which follow the protocol more exactly cannot interoperate with AQ.

https://github.com/ymgaq/AQ/blob/6902ab7fed1ad501ab8c0457a20555822c3b87ae/src/gtp.cpp#L158

**Comment by ymgaq** [comment]
Thank you for pointing out the description. This will be fixed on the next update.

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
