### ISSUE TITLE
AQ  is not responding to the command "name"  when attaching it to GoGui

### ISSUE THREAD

**Issue by ryanzao1105** [ymgaq/AQ#78]
- @ymgaq 

the GoGui says  the program is not responding to the command "name"  when i attach AQ . so how to fix it?
![360 -201484484](https://user-images.githubusercontent.com/25440485/36076690-a259d45a-0f9a-11e8-8971-c071a134d5db.jpg)

**Comment by ymgaq** [comment]
First of all, you should select 'Wait' several times. If the program doesn't launch, push 'Terminate' and see the 'GTP shell' in ```Menu > Tools > GTP Shell```, then you can get much information.

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
