### ISSUE TITLE
For AQ training

### ISSUE THREAD

**Issue by techkkab** [ymgaq/AQ#79]
Thanks for amazing go program.

You inserted training codes in AQ. right? (in feed_tensor.cpp..MakeLearningData)

Then how can I train Supervised Learning with AQ.

Can you explain training methods in details?

**Comment by ymgaq** [comment]
Please wait until learning code will be made public in a future version.
Right now, [Pyaq](https://github.com/ymgaq/Pyaq) , which is a educational code written in Python, will help you to know the learning method of AQ.
(However, note that it is just tiny implementation for Deep Learning tutorial.)

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
