### ISSUE TITLE
AQ victory to grasp the degree

### ISSUE THREAD

**Issue by a22063821** [ymgaq/AQ#8]
From the AQ battle LOG found
AQ winning percentage is usually the leading
Middle game start  winning percentage down

**Comment by ymgaq** [comment]
That is the specification of the search algorithm.

**Comment by a22063821** [comment]
AQ is so fond of tenuki
Win will become lost

**Comment by ymgaq** [comment]
When AQ overestimates the winning percentage and then notices his mistake, it takes such behavior.
AQ is not a perfect player and makes mistake.

**Comment by a22063821** [comment]
thinking on opponent's time
Is it open by default?

**Comment by ymgaq** [comment]
It is the default specification and can not be turned off.
I will consider whether to be able to change by option in a future version.

**Comment by a22063821** [comment]
ok thanks
