### ISSUE TITLE
Incorrect AQ scoring of game.

### ISSUE THREAD

**Issue by jillybob** [ymgaq/AQ#80]
Latest AQ version, running on Sabaki 0.33.2, Windows 10, CPU i5-6500, GPU Nvidia GTX 970

__________________________________________
Reproduction procedure.

 I played this game against Leela 0.11 on OGS with Chinese scoring 7.5 Komi in config file and sabaki. The end game score was W+0.5. However AQ (black) had winrate about 99% and kept playing moves. 

Here is the game: 
https://online-go.com/game/11644066

SGF : https://online-go.com/api/v1/games/11644066/sgf

Load Sabaki 0.33.2 on Windows, attach AQ with following config file, no commands within sabaki and run the game.

https://i.imgur.com/qwOWir0.png
 https://i.imgur.com/ZuWfW8T.png
https://i.imgur.com/H2hU6OT.png
https://i.imgur.com/vbjFn4j.png

At move 305, AQ is showing 93.6 win victory when points are W+1.5
___________________________________________________________________________

AQ config file:

```
### Hardware setting ###
# Set number of 1-8 for 'gpu count'.
# 'thread count' is number of the total usable threads.
-gpu count =1
-thread count =4

### Time contorol setting ###
-main time[sec] =0
-byoyomi[sec] =7
-emergency time[sec] =1

### Thinking setting ###
-japanese rule =off
-komi =7.5
-symmetrical index =8
-use pondering =on
-mimic go =off
-never resign =off

### File settings ###
# Use 'self match' mode on console for debug.
-self match =off
-save log =on
-pb path =pb
-resume sgf path =

### Cluster settings ###
# Not need to change.
-master =off
-worker =off
-worker count =1
```

**Comment by ymgaq** [comment]
As described in [README](https://github.com/ymgaq/AQ/blob/master/README.md), the latest version was trained with Komi = 6.5. It may misunderstand endgame situation, but it is not a bug.
