### ISSUE TITLE
Graphics card usage questions

### ISSUE THREAD

**Issue by baedaeeun** [ymgaq/AQ#81]
Question 1
My computer is equipped with gtx1080ti. Does adding another type of graphics card to this computer speed up AQ operations? 
(For example, I wonder if adding an additional gtx1060 will help AQ do its calculations)

Question 2
AQ uses a lot of gpu memory. So is it better to add 1060-3g to this computer? Would it be better to add 1050ti-4g?

**Comment by ymgaq** [comment]
I have never used different types of graphics card at the same time and I have not compared GTX 1060 with GTX 1050 Ti, so I can not give useful advice.
