### ISSUE TITLE
AQ suddenly didn't do anything and there is no msg...

### ISSUE THREAD

**Issue by qfitte** [ymgaq/AQ#83]
I don't know what has it happened 
![error](https://user-images.githubusercontent.com/36588142/36349536-a5d7be30-14cc-11e8-96ab-74cd8a5aace0.jpg)
(sometimes suddenly didn't do anything and stay it forever)

Often  AQ suddenly didn't do anything and there is no msg...
Anybody who can tell me why?

It's happened after I added 1 more GPU ( 2 GPU total now)

**Comment by ymgaq** [comment]
I do not know because you do not provide enough information. If TensorFlow's error message comes out, you should avoid it.

**Comment by qfitte** [comment]
Sorry, I also don't have enough information because as I told... There is no message.
I think that isn't AQ bug but windows 10 problem. Maybe cuz of automatically driver update.
In that case, I might should install ubuntu for stable environment.
Thanks a lot for your reply.

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
