### ISSUE TITLE
Where it's possible to get AQ CPU only Linux run file?

### ISSUE THREAD

**Issue by GD-fix** [ymgaq/AQ#85]
I had downloaded and installed bazel 0.7.0-6.1.
After executing:
bazel --output_user_root=/home/INSTall/0Go/AQ-2.1.1 build ...
I have got subfolder 'install', where are next files:
```
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/embedded_tools
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/A-server.jar
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/build-runfiles
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/install_base_key
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/java.version
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/jdk.BUILD
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/libunix.so
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/linux-sandbox
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/process-wrapper
file:///home/INSTall/0Go/AQ-2.1.1/install/a0d1e8ed0fd4b297903a7cbf639a23fb/_embedded_binaries/xcode-locator
```

What file is the AQ run?

**Comment by GD-fix** [comment]
How I understand, there isn't working on [usual systems](https://distrowatch.com/dwres.php?resource=major) AQ CPU only version...

**Comment by ymgaq** [comment]
Please build as follows. The executable file will be created in ```tensorfow/bazel-bin/AQ/src/```.

1. Uncomment `#define CPU_ONLY` in [search.h](https://github.com/ymgaq/AQ/blob/850bcff9b129ccfafa74e1a3a86fdb88de31471f/src/search.h#L18).

2. Git clone and build with bazel.

```
$ cd ~
$ git clone --recursive https://github.com/tensorflow/tensorflow
$ git clone https://github.com/ymgaq/AQ
$ ln -s AQ tensorflow/tensorflow/AQ
$ cd tensorflow
$ ./config
$ cd tensorflow/AQ/src
$ bazel build -c opt --config=monolithic :AQ
$ cp ~/tensorflow/bazel-bin/tensorflow/AQ/src/AQ ~/AQ/AQ
$ cp ~/AQ/prob/* ~/AQ/
```

**Comment by GD-fix** [comment]
I had tried this instruction, except that instead of git clone I had downloaded zip archives and extracted to /home (because that PC is local only).
0) AFTER downloading AQ `Uncomment #define CPU_ONLY in search.h` in its SUBFOLDER src (I had replaced value of node_limit from 16411 to 131075 too)
1) `ln -s AQ-2.1.1 tensorflow-master/tensorflow/AQ`  - doesn't work: must be full path to link goal - `ln -s /home/AQ-2.1.1 tensorflow-master/tensorflow/AQ`
2) `cd tensorflow-master`
3) `./config`    - doesn't work: must be `./configure`   - but doesn't work too: 
```
You have bazel 0.7.0- (@non-git) installed.
Please upgrade your bazel installation to version 0.10.0 or higher to build TensorFlow!
Configuration finished
```

Now I have downloaded non-official from users bazel 0.11.0 (but for Tumbleweed) and experimental bazel 0.9.0 for latest official OpenSUSE distributive Leap 42.3.
I have downloaded non-official experimental tensorfloww 1.4.0 (but for Tumbleweed) and from users tensorflow-bootstrap 1.6.0 for latest official OpenSUSE distributive Leap 42.3 too.

I'll try with these variants, but nevertheless of the results the question is: 
> For what purposes are You using experimental packets?

**Comment by GD-fix** [comment]
I had tried this instruction, except that instead of git clone I had downloaded zip archives and extracted to /home (because that PC is local only).
0) AFTER downloading AQ 'Uncomment #define CPU_ONLY in search.h' in its SUBFOLDER src (I had replaced value of node_limit from 16411 to 131075 too)
1) 'ln -s AQ-2.1.1 tensorflow-master/tensorflow/AQ'  - doesn't work: must be full path to link goal - 'ln -s /home/AQ-2.1.1 tensorflow-master/tensorflow/AQ'
2) 'cd /home/tensorflow-master'
3) './config'    - doesn't work: must be './configure'
4) 'cd tensorflow/AQ/src'
   'bazel build -c opt --config=monolithic :AQ'  - doesn't work:  'ERROR: The 'build' command is only supported from within a workspace.'
2) 'cd /home/tensorflow-master'
3) './configure --workspace /home/tensorflow-master'
4) 'cd tensorflow/AQ/src'
   'bazel build -c opt --config=monolithic :AQ'  - doesn't work:  'ERROR: The 'build' command is only supported from within a workspace.'
2) 'cd /home/tensorflow-master'
3) './configure --workspace /home/tensorflow-master/tensorflow/AQ/src'
4) 'cd tensorflow/AQ/src'
   'bazel build -c opt --config=monolithic :AQ'  - doesn't work:  'ERROR: The 'build' command is only supported from within a workspace.'

**Comment by GD-fix** [comment]
I had tried this instruction, except that instead of git clone I had downloaded zip archives and extracted to /home (because that PC is local only).
0) AFTER downloading AQ `Uncomment #define CPU_ONLY in search.h` in its SUBFOLDER src (I had replaced value of node_limit from 16411 to 131075 too)
1) `ln -s AQ-2.1.1 tensorflow-master/tensorflow/AQ`  - doesn't work: must be full path to link goal - `ln -s /home/AQ-2.1.1 tensorflow-master/tensorflow/AQ`
2) `cd /home/tensorflow-master`
3) `./config`    - doesn't work: must be `./configure`
4) `cd tensorflow/AQ/src`
   `bazel build -c opt --config=monolithic :AQ`  - doesn't work:  `ERROR: The 'build' command is only supported from within a workspace.`
2) `cd /home/tensorflow-master`
3) `./configure --workspace /home/tensorflow-master`
4) `cd tensorflow/AQ/src`
   `bazel build -c opt --config=monolithic :AQ`  - doesn't work:  `ERROR: The 'build' command is only supported from within a workspace.`
2) `cd /home/tensorflow-master`
3) `./configure --workspace /home/tensorflow-master/tensorflow/AQ/src`
4) `cd tensorflow/AQ/src`
   `bazel build -c opt --config=monolithic :AQ`  - doesn't work:  `ERROR: The 'build' command is only supported from within a workspace.`

**Comment by gghideki** [comment]
Don't use symbolic link.  Instead, mv AQ directory to below tensorflow.

**Comment by GD-fix** [comment]
And what argument must be with `./configure --workspace`?

**Comment by gghideki** [comment]
Just --configure is enough.  The steps should be:
$ git clone --recursive https://github.com/tensorflow/tensorflow
$ cd tensorflow
$ git clone https://github.com/ymgaq/AQ
$ ./configure
$ cd AQ/src
$ bazel build -c opt --config=monolithic :AQ
The executable is ../../bazel-bin/tensorflow/AQ/src/AQ.

**Comment by gghideki** [comment]
Sorry, not "--configure" but "./configure".

**Comment by gghideki** [comment]
Sorry again.  The executable is ../../bazel-bin/AQ/src/AQ.

**Comment by gghideki** [comment]
To test AQ:
$ cd ..
$ mv ../bazel-bin/AQ/src/AQ .
$ mv prob/* .
$ ./AQ
configuration loaded.
name
= AQ
version
= 2.1.1
quit
...
=
This version will cause a segmentation fault after quitting.  To fix this:
$ cd src
Edit "cluster.h". (For vim, you'd better ":set fenc=sjis".)
Line 72 should be
    ~Cluster(){ SendCommand("quit"); }
Change this line to
    ~Cluster(){ /* SendCommand("quit"); */ }
Save and exit.  Then build AQ again.
$ bazel clean
$ bazel build -c opt --config=monolithic :AQ
$ cd ..
$ rm -f AQ
$ mv ../bazel-bin/AQ/src/AQ .
./AQ
configuration loaded.
name
= AQ
genmove b
...
= <black's first move>
quit
= finished
$

**Comment by gghideki** [comment]
Why bold letters? :-(

**Comment by GD-fix** [comment]
$ git clone --recursive https://github.com/tensorflow/tensorflow
 doesn't work (because that PC is local only) - I had downloaded zip archive and extracted its content. So:
$ cd tensorflow-master
$ git clone https://github.com/ymgaq/AQ
 doesn't work (because that PC is local only): I had downloaded zip archive and extracted to tensorflow-master. So:
$ ./configure
$ cd AQ-2.1.1/src
$ bazel build -c opt --config=monolithic :AQ-2.1.1
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading [https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz, https://github.com/bazelbuild/rules_closure/archive/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz] to /home/leap/.cache/bazel/_bazel_leap/1cdda3d728287575d7aec871a9c644c3/external/io_bazel_rules_closure/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz: All mirrors are down: [Unknown host: github.com, Unknown host: mirror.bazel.build]
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading [https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz, https://github.com/bazelbuild/rules_closure/archive/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz] to /home/leap/.cache/bazel/_bazel_leap/1cdda3d728287575d7aec871a9c644c3/external/io_bazel_rules_closure/08039ba8ca59f64248bb3b6ae016460fe9c9914f.tar.gz: All mirrors are down: [Unknown host: github.com, Unknown host: mirror.bazel.build]
INFO: Elapsed time: 2.092s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

I have downloaded these 2 packages and shall copy to that folders, but I don't know will it be work or not...

**Comment by GD-fix** [comment]
Error is the same...

**Comment by GD-fix** [comment]
Is it possible to build AQ with cmake instead of bazel (because CPU only version did not appear yet)?

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
