### ISSUE TITLE
how strong is aq on a single gtx 1080ti in terms of estimate cgos elo?

### ISSUE THREAD

**Issue by hydrogenpi** [ymgaq/AQ#87]
<!--
Thank you for reporting issues.
Since the developer is so busy, please understand that unimportant questions or requests may not be responded.

[Before adding an issue]
Please search and check if there are similar issues and questions, including those already closed.

[How to add a new issue]
**Title**
Make it possible to grasp the content of the issue by title only.

  Good: 'Resigns immediately on handicap games'
  Bad: 'some questions', 'a bug'

**Comments**
Please write the contents concisely.
Do not include multiple topics in one issue.

In the case of a bug, please describe the following contents.
+ Execution environment (AQ ver. / OS / CPU / GPU)
+ Reproduction procedure (in detail as much as possible)
+ How to fix it (if you have an idea)

**Labels** (able to attach from the right setting list)
'question': just a question
'enhancement': request for additional functions and improvement
'bug': a bug

Other labels will be judged by the developer, so the reporter should not use it.
--!>

**Comment by Vargooo** [comment]
[](http://www.yss-aya.com/cgos/19x19/bayes.html)

I think  AQ-2.1.1-4t1g  was with a 1080Ti, so, that's 3878 Elo, but this number decreases as time goes by, if you don't play any game, I don't know why.

**Comment by hydrogenpi** [comment]
@Vargooo so is it fair to say that on a single GTX1080ti (running 7700k) that it is better winrate than Ray and also Leela 11 and CrazyStone? Other than Zen, is AQ the best out there right now for a machine on 7700k and GTX1080Ti?

**Comment by Vargooo** [comment]
Yes,  for the moment, it's by far the strongest (but with the rise of Leela Zero, who knows for how long...) In november, I ran with Sabaki, some games against L011OpenCL and CSDL on a computer with 1GPU :
Win10 i7-6700K (4gHz) 32GB 1GTX1080

Even games : AQ beats Leela0110GTP_OpenCL 5-0
H2 : AQ (W) beats Leela0110GTP_OpenCL (B) 4-1 (always by resignation)
So AQ is at least 2 stones stronger 

I tried matches against CSDL (set at 5 Dan)  AQ is at least 3 stones stronger (but you can't use Sabaki with CSDL, you have to enter the moves by hand :o(

The next best program is LZ with [these weights](https://github.com/gcp/leela-zero/issues/884)
AQ is only 1 stone stronger, but with 2GPUs, if you try an AQ v. LZ_20x256network match on your computer, I'd be interested to know the outcome.

**Comment by hydrogenpi** [comment]
So AQ on a powerful GPU is already at least 1 dan pro? 

Haylee on youtube played CrasyStone and Leela a while back, she won but it was always a integrated graphics card. I wonder if she would still win against AQ on 2X 1080Ti

**Comment by Vargooo** [comment]
[From this source](http://computer-go.org/pipermail/computer-go/2018-January/010682.html)

you can see that with only 1GPU it's already veeeery strong :o)

AQ-2.1.1-4t1g     (1g is for 1GPU I think)  is around Fan Hui or Alfago Fan's level

**Comment by hydrogenpi** [comment]
Wow that is pretty cool. Interesting that on Haylee's channel she hasn't played AQ on high GPU yet :)

**Comment by hydrogenpi** [comment]
BTW rumors are that when the GTX 2080 debuts in April, it will be only for gaming and not for AI, and Nvidia is selling seperate versions of the gpu chips, one for only gaming, one for only AI, and one for only bitcoin mining. This reminds me back when before all the AI/bitcoin fuss, when a few years back Nvidia purposefully handicapped the floating point precision of their gtx graphics cards so to preserve value of their Titan's which were used for scientific research, so that the GTX graphics card were crippled to 1/32th of what they were capable of doing when it came to FPU... Hopefully when the GTX2080comes out they won't do the same trick and make it useless for deep learning and only useful for playing games...

**Comment by ymgaq** [comment]
AQ-2.1.1-4t1g used not GTX1080Ti but GTX1080. AQ may be able to evaluate data 10-15% faster with GTX 1080Ti.

AQ has been officially running at [Yugen no ma](http://u-gen.nihonkiin.or.jp/), which is a Go server managed Nihon Ki-in, since last week and the result of 100 games against Japanese professional players was 95-5 (win-loss). The hardware is dual GPUs (GTX 1080Ti) and i7-8700K. If you use a single GTX 1080Ti, the elo rating will be reduced by 100-120.

**Comment by hydrogenpi** [comment]
@ymgaq  thanks for the response. Wow it seems like 95-5 means AQ is already at or above basic Pro levels. How does your program mainly differ from Leela zero and the MiniGo (AlphaGo recreation) that Andrew Jackson of Google is trying to make? Would you say there is the possibility of AQ keep improving or what is the biggest limitations.

**Comment by hydrogenpi** [comment]
Haylee will play against AQ tomorrow!

**Comment by hydrogenpi** [comment]
BTW have you tried AQ on the Nvidia Titan V?! @ymgaq

**Comment by Vargooo** [comment]
Sadly , the game will be played on poor hardware (gtx970 and i5)

**Comment by hydrogenpi** [comment]
The bot won!

https://online-go.com/game/11903008

**Comment by hydrogenpi** [comment]
I'm going to try AQ with 8 x Nvidia V100 cards and test the performance of how it scales. 

https://aws.amazon.com/ec2/instance-types/p3/

Its interesting anyone can download open source AQ and rent some Nvidia V100 cards and play at AlphaGo levels !

**Comment by jillybob** [comment]
> AQ-2.1.1-4t1g used not GTX1080Ti but GTX1080. 
> The hardware is dual GPUs (GTX 1080Ti) and i7-8700K. If you use a single GTX 1080Ti, the elo rating will be reduced by 100-120.

The ELO reduction estimate is incorrect. You had mentioned Dual 1080Ti's (~7820 playouts  per second) are 100-120 ELO stronger than ~3,400 playouts/second (Single 1080)

At 20,000 playouts per second (using 4x v100 GPU) and 24V cores, "AquaTest" (AQ 2.1.1 bot) is only 60 ELO stronger than "AQ-2.1.1-4t1g" which is ~3,400 playouts/second. 

Therefore, the ELO gain between 3,400 playouts/second and 7,820 playouts per second can not be greater than 60 ELO, I would guess about 20-40 ELO increase going from a single 1080 to dual 1080 Ti.

**Comment by Vargooo** [comment]
It's AQ's author who estimated the 100-120 Elo decrease..

Envoyé depuis Yahoo Mail pour Android 
 
  Le mer., mars 14, 2018 à 12:07, jillybob<notifications@github.com> a écrit :   

AQ-2.1.1-4t1g used not GTX1080Ti but GTX1080.
The hardware is dual GPUs (GTX 1080Ti) and i7-8700K. If you use a single GTX 1080Ti, the elo rating will be reduced by 100-120.


The ELO reduction estimate is incorrect. You had mentioned Dual 1080Ti's (~7820 playouts per second) are 100-120 ELO stronger than ~3,400 playouts/second (Single 1080)

At 20,000 playouts per second (using 4x v100 GPU) and 24V cores, "AquaTest" (AQ 2.1.1 bot) is only 60 ELO stronger than "AQ-2.1.1-4t1g" which is ~3,400 playouts/second.

Therefore, the ELO gain between 3,400 playouts/second and 7,820 playouts per second can not be greater than 60 ELO, I would guess about 20-40 ELO increase going from a single 1080 to dual 1080 Ti.

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
