### ISSUE TITLE
AWS P3 (Nvidia V100) instances not getting the expected playouts

### ISSUE THREAD

**Issue by hydrogenpi** [ymgaq/AQ#89]
I rented a p3.2xlarge instance on aws ec2 and its only getting roughly twice the # of playouts as a gtx 970 even though I set the right config and installed the correct drivers. This is for on Windows Server 2012R2, using the latest Nvidia tesla driveers for that server version and the CUDA 9.1

Does anyone come across this issue? 

GTX 970 : https://i.imgur.com/nThJgTj.png

Nvidia V100 : https://u.cubeupload.com/zwBXZx.png

https://github.com/gcp/leela-zero/issues/985

<!--
Thank you for reporting issues.
Since the developer is so busy, please understand that unimportant questions or requests may not be responded.

[Before adding an issue]
Please search and check if there are similar issues and questions, including those already closed.

[How to add a new issue]
**Title**
Make it possible to grasp the content of the issue by title only.

  Good: 'Resigns immediately on handicap games'
  Bad: 'some questions', 'a bug'

**Comments**
Please write the contents concisely.
Do not include multiple topics in one issue.

In the case of a bug, please describe the following contents.
+ Execution environment (AQ ver. / OS / CPU / GPU)
+ Reproduction procedure (in detail as much as possible)
+ How to fix it (if you have an idea)

**Labels** (able to attach from the right setting list)
'question': just a question
'enhancement': request for additional functions and improvement
'bug': a bug

Other labels will be judged by the developer, so the reporter should not use it.
--!>

**Comment by stormsson** [comment]
@hydrogenpi  did you ever find a solution on how to use full v100 ?

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
