### ISSUE TITLE
.pb file is too large, is there any way to decrease?

### ISSUE THREAD

**Issue by cheasonxie** [ymgaq/AQ#93]
I have port the source code to android, and run ok, but I think sl.pb and vl.bp is too large to a android apk.
I try tensorflow's tool quantize_graph, file size is decreased, but run error.
is there any other way to decrease?

**Comment by hydrogenpi** [comment]
can u do the same for Leela Zero?

**Comment by cheasonxie** [comment]
@hydrogenpi I have also port to leela zero to android, it work on cpu only, but it's very very slow.
if using gpu, there some error on opencl. 
I think there is one way to try, on cpu only mode, renderscript can be used to do sgemm.

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
