### ISSUE TITLE
Change in Komi Doesnt effect AQ

### ISSUE THREAD

**Issue by Climu1d** [ymgaq/AQ#94]
I wanted to see if AQ will change the way it plays by changing the komi so I decided to change the komi to 20.5.... but when i did and i let AQ think, the evaluation/win percentage did not change at all and I didnt see a change of pace or anything in AQ's play ..... is there an issue that komi doesnt effect AQ or is AQ just biult to run on a certain amount komi, being 6.5 or 7.5.... I will add that it's win % does drop when using handicap stones..... but the change in komi either directly from config settings or from sabaki itelf does nothing to AQ ;/

**Comment by deasuke** [comment]
I think you need re-trained network weights with changed komi for it.

**Comment by Climu1d** [comment]
and how do i get that? I dont even know what it is lol @_@

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
