### ISSUE TITLE
Please make an option to turn off skip search

### ISSUE THREAD

**Issue by sunmier** [ymgaq/AQ#95]
AQ skips its search when stand_out || enough_game || almost_win.
Please make an option to the aq_config which enables to turn on/off skip search.

**Comment by iteachcs** [comment]
I would like to have such an option too.  I had a game where AQ skipped search and made a blunder at the end game.

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
