### ISSUE TITLE
Doesn't compile with bazel

### ISSUE THREAD

**Issue by GD-fix** [ymgaq/AQ#96]
I had tried this (#85) instruction, except that instead of git clone I had downloaded zip archives and extracted to /home (because that PC is local only).
0) AFTER downloading AQ `Uncomment #define CPU_ONLY in search.h` in its SUBFOLDER src (I had replaced value of node_limit from 16411 to 131075 too)
1) `ln -s AQ-2.1.1 tensorflow-master/tensorflow/AQ`  - doesn't work: must be full path to link goal - `ln -s /home/AQ-2.1.1 tensorflow-master/tensorflow/AQ`
2) `cd /home/tensorflow-master`
3) `./config`    - doesn't work: must be `./configure`
4) `cd tensorflow/AQ/src`
   `bazel build -c opt --config=monolithic :AQ`  - doesn't work:  `ERROR: The 'build' command is only supported from within a workspace.`
2) `cd /home/tensorflow-master`
3) `./configure --workspace /home/tensorflow-master`
4) `cd tensorflow/AQ/src`
   `bazel build -c opt --config=monolithic :AQ`  - doesn't work:  `ERROR: The 'build' command is only supported from within a workspace.`
2) `cd /home/tensorflow-master`
3) `./configure --workspace /home/tensorflow-master/tensorflow/AQ/src`
4) `cd tensorflow/AQ/src`
   `bazel build -c opt --config=monolithic :AQ`  - doesn't work:  `ERROR: The 'build' command is only supported from within a workspace.`

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
