### ISSUE TITLE
Can someone create a mobile app for Leela Zero as well now that AQ got one?

### ISSUE THREAD

**Issue by hydrogenpi** [ymgaq/AQ#97]
<!--
Thank you for reporting issues.
Since the developer is so busy, please understand that unimportant questions or requests may not be responded.

[Before adding an issue]
Please search and check if there are similar issues and questions, including those already closed.

[How to add a new issue]
**Title**
Make it possible to grasp the content of the issue by title only.

  Good: 'Resigns immediately on handicap games'
  Bad: 'some questions', 'a bug'

**Comments**
Please write the contents concisely.
Do not include multiple topics in one issue.

In the case of a bug, please describe the following contents.
+ Execution environment (AQ ver. / OS / CPU / GPU)
+ Reproduction procedure (in detail as much as possible)
+ How to fix it (if you have an idea)

**Labels** (able to attach from the right setting list)
'question': just a question
'enhancement': request for additional functions and improvement
'bug': a bug

Other labels will be judged by the developer, so the reporter should not use it.
--!>

**Comment by ddugovic** [comment]
I wonder what the power consumption would be like for such an app (given the current state of the engine).

**Comment by hydrogenpi** [comment]
which one? aq or lz

**Comment by ddugovic** [comment]
Honestly, I'm curious about both, though I expect Leela Zero would melt your phone in half.

**Comment by alreadydone** [comment]
Here https://github.com/gcp/leela-zero/issues/591#issuecomment-360826163 is an interested developer. People talked about 5x64 or 6x128 networks, but AQ's networks seem larger? (Not clear about the architectures; the only thing I can find are conv17 in vl.pb and conv21 in sl.pb). For small networks, it's probably necessary to incorporate a ladder module as the AQ Android developer did. Anyway, why are you posting here instead at gcp/leela-zero?

**Comment by hydrogenpi** [comment]
This mobile app is done by a third party not the aq dev himself. so I posted here so mayb e he can se eit and do one for LeelaZ as well!

**Comment by alreadydone** [comment]
It's good for him to see it, but for LZ mobile we need developers familiar with either the LZ codebase or with Android or both, but not so much with AQ.

**Comment by hydrogenpi** [comment]
https://github.com/gcp/leela-zero/issues/1136

**Comment by afalturki** [comment]
No plans for iOS?

**Comment by hydrogenpi** [comment]
Andriod is apk

**Comment by Vargooo** [comment]
@ddugovic : power consumption is indeed enormous with AQ-Android, my new S8+ is hot after 30 min of AI v. AI games and more than 15% battery has been used

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
