### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by GD-fix** [ymgaq/AQ#99]
OS: OpenSUSE Leap 42.3.
Installed by Yast2 Program Management: bazel-0.11.0-8.4; tensorflow-1.4.0-3.14.
Command: ...AQ-2.1.1/src> bazel build -c opt --config=monolithic :AQ
ERROR: The 'build' command is only supported from within a workspace.

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
